name: Automatically Deployment

on: 
  push:
    branches: [ distribute ]
  pull_request: 
    branches : [ distribute ]

jobs:
  build:
    runs-on: ubuntu-latest

    # 해당 Job의 이름을 아래와 같이 설정하여 Actions 탭에서 확인할 수 있게 설정합니다.
    name: Deploying to surge
    env:
      REACT_APP_MONGOURI : ${{ secrets.REACT_APP_MONGOURI }}

    steps:
      uses: npm run dev
      run: echo $REACT_APP_MONGOURI