name: Automatically Deployment

on: 
  push:
    branches: [ distribute ]
  pull_request: 
    branches : [ distribute ]

jobs:
  deployment:
    runs-on: ubuntu-latest

    # 해당 Job의 이름을 아래와 같이 설정하여 Actions 탭에서 확인할 수 있게 설정합니다.
    name: Deploying to surge

    steps:

      # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_MONGOURI=$REACT_APP_MONGOURI" >> .env.production
        env:
          REACT_APP_MONGOURI : '${{ secrets.REACT_APP_MONGOURI }}'
          NODE_ENV : 'production'
          
